import { concept } from "./factory";

const family = ["teaching"] as const;

export const teachingConcepts = [
  concept({ id: "lesson-planning", category: "skill", es: "Planificación didáctica", en: "Lesson planning", families: [...family], esAliases: ["planificación de clases", "planes de clase", "planificación educativa"], enAliases: ["lesson plans", "instructional planning", "educational planning"] }),
  concept({ id: "classroom-management", category: "skill", es: "Gestión del aula", en: "Classroom management", families: [...family], esAliases: ["manejo del aula", "gestión de grupo", "manejo de grupo"], enAliases: ["class management", "manage classroom", "behavior management"] }),
  concept({ id: "student-assessment", category: "responsibility", es: "Evaluación del aprendizaje", en: "Student assessment", families: [...family], esAliases: ["evaluación de estudiantes", "evaluación formativa", "evaluación educativa"], enAliases: ["learning assessment", "formative assessment", "assess student progress"] }),
  concept({ id: "curriculum-development", category: "skill", es: "Desarrollo curricular", en: "Curriculum development", families: [...family], esAliases: ["diseño curricular", "planificación curricular", "desarrollo del currículo"], enAliases: ["curriculum design", "curriculum planning", "develop curriculum"] }),
  concept({ id: "curriculum-adaptation", category: "skill", es: "Adaptación curricular", en: "Curriculum adaptation", families: [...family], esAliases: ["adecuación curricular", "adaptaciones curriculares", "ajustes curriculares"], enAliases: ["curriculum differentiation", "curriculum accommodations", "adapt curriculum"] }),
  concept({ id: "educational-technology", category: "tool", es: "Tecnología educativa", en: "Educational technology", families: [...family], esAliases: ["herramientas digitales educativas", "tecnologías para el aprendizaje", "TIC educativas"], enAliases: ["education technology", "edtech", "digital learning tools"] }),
  concept({ id: "learning-management-system", category: "tool", es: "Plataforma educativa", en: "Learning management system", families: [...family], esAliases: ["aula virtual", "plataforma de aprendizaje", ["LMS", "abbreviation"]], enAliases: ["learning platform", "virtual classroom", ["LMS", "abbreviation"]] }),
  concept({ id: "inclusive-education", category: "methodology", es: "Educación inclusiva", en: "Inclusive education", families: [...family], esAliases: ["enseñanza inclusiva", "inclusión educativa", "atención a la diversidad"], enAliases: ["inclusive teaching", "inclusive classroom", "support diverse learners"] }),
  concept({ id: "student-feedback", category: "responsibility", es: "Retroalimentación a estudiantes", en: "Student feedback", families: [...family], esAliases: ["retroalimentación educativa", "feedback a estudiantes", "devolución pedagógica"], enAliases: ["learner feedback", "provide student feedback", "academic feedback"] }),
  concept({ id: "family-communication", category: "responsibility", es: "Comunicación con familias", en: "Family communication", families: [...family], esAliases: ["comunicación con representantes", "reuniones con padres", "atención a familias"], enAliases: ["parent communication", "family engagement", "parent meetings"] }),
  concept({ id: "student-support", category: "responsibility", es: "Acompañamiento estudiantil", en: "Student support", families: [...family], esAliases: ["acompañamiento a estudiantes", "orientación estudiantil", "apoyo al estudiante"], enAliases: ["learner support", "student guidance", "support students"] }),
  concept({ id: "teaching-methodologies", category: "methodology", es: "Estrategias de enseñanza", en: "Teaching strategies", families: [...family], esAliases: ["estrategias didácticas", "metodologías de enseñanza", "métodos de enseñanza"], enAliases: ["instructional strategies", "teaching methods", "instructional methods"] }),
] as const;
